#!/bin/sh

echo "Executing pre-commit hook..."
gitRootDir=$(git rev-parse --show-toplevel)
if ! "$gitRootDir"/.ci/debendencies.sh ; then exit 1; fi
if ! "$gitRootDir"/.ci/shelllint.sh ; then exit 1; fi
if ! "$gitRootDir"/.ci/xmllint.sh ; then exit 1; fi
if ! "$gitRootDir"/.ci/javalint.sh; then exit 1; fi
exit 0
